// <auto-generated />
namespace trongduy201103856.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class khoitaocacchucnangnguoidung : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(khoitaocacchucnangnguoidung));
        
        string IMigrationMetadata.Id
        {
            get { return "202303141553541_ khoi tao cac chuc nang nguoi dung"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
